#!/usr/bin/env bash
set -euo pipefail

# This script manages the lifecycle of the "dtgeofinder" Docker container.
# 1. Stops and removes any existing "dtgeofinder" container to ensure a clean start.
# 2. Removes the existing SQLite database file on the host to reset the database state.
# 3. Prepares host-side output directories to store various product outputs generated by the container.
# 4. Runs a new "dtgeofinder" container with specific volume mappings and environment settings.
#
# Volume mappings:
# - Host's "host_shared" directory is mounted into the container for shared data access.
# - SeisComP log directory is mapped to allow persistent logging.
# - Output directories for FinDer, shakemap, and PyFinder are mapped to host directories to persist results.
#
# The "--platform linux/amd64" flag forces the container to run with the amd64 architecture, ensuring compatibility
# on systems where the default architecture might differ (e.g., Apple M1/M2 chips).
#
# The container runs "bash -lc 'tail -f /dev/null'" to keep the container alive indefinitely without exiting,
# allowing interactive or background processes to be executed within the container after startup.

docker stop dtgeofinder 2>/dev/null || true
docker rm dtgeofinder 2>/dev/null || true

# If exists, remove the database to have a clean state.
FILE="$(pwd)/host_shared/seiscomp_db/db.sqlite"

if [ -f "$FILE" ]; then
  rm "$FILE"
fi

# Prepare host-side output directories for products
HOST_OUT="$(pwd)/host_shared/docker-output"
mkdir -p "$HOST_OUT/FinDer-output" "$HOST_OUT/shakemap" "$HOST_OUT/PyFinder-output"

# Run the Docker container
docker run -d \
  --name dtgeofinder \
  --platform linux/amd64 \
  -u sysop \
  -w /home/sysop \
  -e SEISCOMP_ROOT=/opt/seiscomp \
  -v "$(pwd)/host_shared:/home/sysop/host_shared" \
  -v "$(pwd)/host_shared/.seiscomp_log:/home/sysop/.seiscomp/log" \
  -v "$HOST_OUT/FinDer-output:/home/sysop/.seiscomp/FinDer-output" \
  -v "$HOST_OUT/shakemap:/home/sysop/shakemap_profiles/default/data" \
  dtgeofinder:master \
  bash -lc "tail -f /dev/null"

echo "Container 'dtgeofinder' is running in the background."
# View logs just in case
docker logs dtgeofinder
